### ISSUE TITLE
clang is not supported?

### ISSUE THREAD

**Issue by toge** [peter-winter/ctpg#15]
When I try to use ctpg with clang13, clang fails to build.
It works correctly in gcc11.
Is clang not supported?

```
include/ctpg.hpp:1466:18: error: function 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' with deduced return type cannot be used before it is defined
        auto p = create_regex_parser(a);
                 ^
include/ctpg.hpp:1460:20: note: 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' declared here
    constexpr auto create_regex_parser(Builder& b);
                   ^
include/ctpg.hpp:1463:24: error: no return statement in constexpr function
    constexpr size32_t analyze_dfa_size(const char (&pattern)[N])
                       ^
include/ctpg.hpp:1612:25: error: function 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' with deduced return type cannot be used before it is defined
        auto p = regex::create_regex_parser(a);
                        ^
include/ctpg.hpp:1460:20: note: 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' declared here
    constexpr auto create_regex_parser(Builder& b);
                   ^
include/ctpg.hpp:1641:29: error: function 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' with deduced return type cannot be used before it is defined
            auto p = regex::create_regex_parser(a);
                            ^
include/ctpg.hpp:1460:20: note: 'create_regex_parser<ctpg::regex::dfa_size_analyzer>' declared here
    constexpr auto create_regex_parser(Builder& b);
                   ^
include/ctpg.hpp:831:36: error: in-class initializer for static data member is not a constant expression
    static const size_t dfa_size = regex::analyze_dfa_size(Pattern);
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by peter-winter** [comment]
Unfortuanately not yet. But this is high on my priority list so stay tuned.

**Comment by toge** [comment]
Thank you for quick response!
I'm waiting for it.

**Comment by peter-winter** [comment]
I have some bad news. Unfortunately it is a much bigger issue than I thought.
After the errors you reported, clang seems to have a problem to compile internal regex parser for ctpg lexer.
The regex parser is written in ctpg itself (how cool is that!) and this somehow breaks clang, not sure why.

**Comment by peter-winter** [comment]
Ok, it turns out that increasing -fconstexpr-steps solves the issue. The error however did not suggest this solution. It complained about static const class member being initialized by a non-const.

**Comment by peter-winter** [comment]
Ok. I think #17 solved it. Due to massive compilation time optimization clang now does not have any issues with examples.
Keep in mind however, that the clang bug still exists, so when grammar gets too complicated you probably won't get an apropriate message about constexpr calculations exceeding a limit, but a weird error instead. 
I'll try to prepare a simple code snipped and raise an issue for clang.
