### ISSUE TITLE
Regex Fails to Match

### ISSUE THREAD

**Issue by BenHanson** [peter-winter/ctpg#20]
```
using namespace ctpg;
using namespace ctpg::buffers;

constexpr char number_pattern[] = "0|[1-9][0-9]*";
constexpr ctpg::regex::expr<number_pattern> r;
const bool match = r.match(string_buffer("0"));

```
match returns false, whereas matching `string_buffer("1")` returns true.

**Comment by peter-winter** [comment]
Unfortuantely confirmed. Easy fix. This is a regression introduced when changed regex parserto have a handcrafted lexer. A corner case was added and no unit test covered it. Already have a fix.

**Comment by peter-winter** [comment]
Should b fixed now. Added appropriate unit test.

**Comment by BenHanson** [comment]
Thanks! Will test now.
