### ISSUE TITLE
Lifetime Warning from VC++

### ISSUE THREAD

**Issue by BenHanson** [peter-winter/ctpg#23]
Not sure if this is a valid warning, but here it is:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	C26800	Use of a moved from object: ''(*start)'' (lifetime.1).	scratchpad	D:\Ben\Dev\ctpg-master\include\ctpg.hpp	2503	

```

**Comment by peter-winter** [comment]
What msvc (cl) version? The only one I tested so far is 19.30, which does not issue this warning, at least on default settings.
All the tests pass on cl 19.30, but until I set up an automatic build I'm not officilly supoting msvc.

**Comment by BenHanson** [comment]
I say warning, but this is actually the built in code analysis in the IDE I believe.

**Comment by peter-winter** [comment]
Well, in this case this is a non issue. IDE tools tend to fail when encounter complex templates.

**Comment by BenHanson** [comment]
Right, I wondered about that. So long as you are happy with the code on line 2503.

If you run cl.exe with /W4 and /std:c++17 you will get a load of narrowing warnings BTW.

**Comment by peter-winter** [comment]
Are you running latest master (1.3.6) ? Asking because I just fixed bunch of msvc warnings.

**Comment by BenHanson** [comment]
I just took latest to confirm. Note this is with warning level 4 (/W4)

**Comment by peter-winter** [comment]
Ok. So are you fine closing this one and addressing /W4 and adequate ones in gcc in a separate issue?

**Comment by BenHanson** [comment]
Sure, I have plenty of other tests to run in the meantime.
