### ISSUE TITLE
Make tests and examples executables conditional

### ISSUE THREAD

**Issue by JPenuchot** [peter-winter/ctpg#28]
Hi,

Having test and example executables optionally removed would be nice to have as it would cut down installation and package generation times (I'm writing an AUR package for ctpg right now btw).

Thanks for you work so far :)

Regards,
Jules

**Comment by peter-winter** [comment]
Not sure what you mean. The examples are not built at all in the cmake. You don't have to run tests either. I'm not really familiar how AUR packages work.

**Comment by JPenuchot** [comment]
Tests are being built when `make install` is called, it doesn't break packaging at all but it makes installation dependent on having a compiler installed and add an unnecessary step for installation. AUR packages provide scripts to build and install software, users have to build them at each update, and thus being able to remove an unnecessary compilation step for installation would allow for quicker install for AUR package users. As I said it's just a nice-to-have, not a critical issue at all.

**Comment by peter-winter** [comment]
I'm ok doing this improvement. Can you save me some time and please provide a patch for CMakeLists.txt so that tests are built only for a specific 'test' target?

**Comment by peter-winter** [comment]
Thanks for help. It all looks fine.

**Comment by peter-winter** [comment]
Let me know when this reaches AUR, I'll mention it in the installation notes.
