### ISSUE TITLE
Parsing exponent notation in json-parser

### ISSUE THREAD

**Issue by nandanvasudevan** [peter-winter/ctpg#36]
I just saw that the `to_js_number()` **does not work** when the exponent does not have a sign (like 1.0e8).
A quick look into the JSON schema tells me that it is allowed.

![image](https://user-images.githubusercontent.com/28172619/149721958-bbabdadf-b769-45b5-90ac-83a048c4d46c.png)

Was this missed or is support for these not required?

Here is a simple fix anyway. I am happy to provide a pull request if this is necessary.
Just confused right now.

https://godbolt.org/z/7bo3d41K6

**Comment by peter-winter** [comment]
This is my mistake. First of all a fix to the regex is needed. The way you fixed it in to_js_number is way too complicated.
I would do it like this:
```
exp_minus = *it == '-';
if (*it == '-' || *it == '+') ++it;
```

**Comment by nandanvasudevan** [comment]
I agree.
Please go ahead!

**Comment by peter-winter** [comment]
Fixed
