### ISSUE TITLE
Ignore all whitespaces but newlines

### ISSUE THREAD

**Issue by stephanroslen** [peter-winter/ctpg#37]
First of all I really like your library and am very curious to learn about the implementation details and tinker around with it. I just had one question:

Is there a way to ignore all whitespaces but newlines to define a language where newlines are a syntax element yet? Like e.g. the HTTP protocol?

**Comment by peter-winter** [comment]
Unfortunately no.

**Comment by stephanroslen** [comment]
I had a similar idea of making all whitespaces configurable separately through a `bitset` and `set_skip_whitespace(true)` would just set all bits to true. I just implemented the `dont_skip_newline` variant you proposed and will open a MR.
