### ISSUE TITLE
how long to next release ?

### ISSUE THREAD

**Issue by 95833** [peter-winter/ctpg#52]
Cannot place regex_term "[0-9]+|[0-9]+." or both two regex_term "[0-9]+" and "[0-9]+." in terms now?

**Comment by peter-winter** [comment]
Why would you do this? It is the same term.

**Comment by peter-winter** [comment]
There isn't much to release really. I'm sort of waiting until there are some good ideas on how to improve the library.

**Comment by stamnug** [comment]
> Why would you do this? It is the same term.
for recognize following:
int : "[0-9]+" and float : "[0-9]+\\.[0-9]+"
or
float self " [0-9]\\.[0-9]+[Ee]-?[0-9]+ | [0-9]+[Ee]-?[0-9]+ | [0-9]+\\.[0-9]+"
or
even bool "true|false" and variable "[a-z][a-zA-Z0-9]+"
and so on.

place them in terms will is an error.

**Comment by stamnug** [comment]
it should be an problem about lexer priority. would you fix it ?

**Comment by peter-winter** [comment]
Can you please provide some code which isn't working?

**Comment by stamnug** [comment]
> Can you please provide some code which isn't working?

Might I writen mistake.  the error of string cannot be reappeared and has been deleted due to finding a new lib(https://github.com/metthal/pog). the following is the code of regex error:
```
#include <ctpg/ctpg.hpp>
#include <iostream>
#include <charconv>

using namespace ctpg;
using namespace ctpg::buffers;

constexpr nterm<int> list("list");

constexpr char number_pattern[] = "[0-9]+\\.[0-9]+[Ee]-?[0-9]+|[0-9]+[Ee]-?[0-9]+";
constexpr regex_term<number_pattern> number("number");

constexpr parser p(
    list,
    terms(
        number
    ),
    nterms(
        list
    ),
    rules(
        list(number) >= [](const auto& n) { 
            return 0; 
        }
    )
);

int main(int argc, char* argv[])
{
    if (argc < 2)
        return -1;
    auto res = p.parse(string_buffer(argv[1]), std::cerr);
    bool success = res.has_value();
    if (success)
        std::cout << res.value() << std::endl;
    return success ? 0 : -1;
}
```

**Comment by 95833** [comment]
Maybe the function of mode switcher need to be added also.

**Comment by peter-winter** [comment]
I know you closed it, but actually you were encountering a bug which I am just fixed. The problem was with regexes of the form:
a*b|a*
a+b|a+
