### ISSUE TITLE
Constexpr parsing of an array of ints

### ISSUE THREAD

**Issue by haasdo95** [peter-winter/ctpg#69]
Hello!... Hope you're doing great!

I am having some difficulty parsing arrays/lists at compile time. As a minimal example, suppose we have a string literal "1, 1, 2, 3, 3, 6..." with N numbers and we're trying to parse the given list into an std::array<int, N>. At the moment, I do not how to specify grammar rules since nterm requires a full type as its value type.

Stuff like this is possible with hand-written parser since we can always statically count the numbers and put them in the array. But here it seems that we need a production rule from std::array<N-1> to std::array<N>...

It'll be great if you could give me a pointer on how to do this.  

All the best.

**Comment by peter-winter** [comment]
Well, first thing that comes to mind is parsing the thing twice, once returning the constexpr number of elements, and using that for type definition for the second parser. You would need some function template to not duplicate the parser, because the grammar root needs two different value types, a size type first and then array type.

Second thing is actually assuming the maximum number of elements, which is easy to do (number of characters in a string / 2 ).

**Comment by haasdo95** [comment]
I experimented with this idea (parsing a list of string and storing them in an array of string_view) and I got this error

ctpg.hpp:3366:13: error: accessing uninitialized member ‘ctpg::stdex::cvector<unsigned int, 506, void>::current_size’

This is apparently caused by a push_back to the cv_vector.
Could you please give me a pointer about what might have caused this?
Thanks in advance!

**Comment by haasdo95** [comment]
Turns out that it is a C++ 20 issue... Reverting to C++17 fixes it. 
Sorry for the inconvenience.

**Comment by haasdo95** [comment]
FYI I got it to work with Cpp20 by making a small change...
At line 2167 I changed 
````C++
struct state {
      situation_vector all_situations_vec = {};
      situation_set kernel = {};
      situation_vector situations_by_symbol[symbol_count] = {};
};
````
into 
````C++
struct state {
        constexpr state(): all_situations_vec{}, kernel{}, situations_by_symbol{} {}
        situation_vector all_situations_vec = {};
        situation_set kernel = {};
        situation_vector situations_by_symbol[symbol_count] = {};
};
````
And now everything works :b
I assume it has to do with how things are initialized in C++ arrays.

**Comment by peter-winter** [comment]
Thanks a lot!
