### ISSUE TITLE
Invoking undefined behaviour when using an rvalue in the constructor of stdex::cvector

### ISSUE THREAD

**Issue by hrco159753** [peter-winter/ctpg#7]
This is my first pull request :fireworks:, so yeah..., but here you're invoking an undefined behaviour(for _count_ larger then 1) by moving an rvalue into the `emplace_back` function _count_ times. It'd be fine if you were to move only once, but because you're moving it more than once you can't really expect any other element after the first to be in the valid state inside the _the_data_ member field.

https://github.com/peter-winter/ctpg/blob/99af8d2f712a3bfdfbe37d858fac391da2c78240/ctpg.hpp#L114-L119

**Comment by peter-winter** [comment]
Thanks. It is not used anywhere, this constructor literally doesn't ake sense.

**Comment by peter-winter** [comment]
Fixed
