### ISSUE TITLE
[Question] how to make the lexer NOT match a particular string

### ISSUE THREAD

**Issue by haasdo95** [peter-winter/ctpg#70]
As title. I am wondering if we currently have the ability of not matching a particular string/prefix, like the "?!" in standard regex. 
Thinking it might be useful for implementing keywords. 
Thanks!
All the best.

**Comment by peter-winter** [comment]
Not at the moment. At least not in an easy way.
You don't need this to implement keywords though, just place them in front of the more general 'identifier' regex and you'll be fine. Terms order determines their precedence.

**Comment by haasdo95** [comment]
That's actually great to know... 
Thanks a lot!
Have a good one.
