### ISSUE TITLE
Simple expression example and AST

### ISSUE THREAD

**Issue by iglesias** [peter-winter/ctpg#73]
Hi, I started with the `examples/simple-expr-parser.cpp` and I am wondering if it would be possible to retrieve from the `parser p` a type, or some other data, to inspect (or derive from it, if needed) the AST associated to an expression.

For example, when either running the program `./simple-expr-parser '3*(1-5)'` or writing code `p.parse(cstring_buffer("3*(1-5)")` is there somewhere, even if internal, something like `o_mul<<number<3>, o_minus<number<1>, number<5>>>`?

Thank you very much in advance for any help!

**Comment by peter-winter** [comment]
Sure. Take a look at a json parser example. I creates standard containers (like std::map, std::vector, std::string), however I'm sure you can create whatever else you like.
If you want AST to be constexpr, it is a bit more difficult, I do this in ctjs example (creates constexpr json representation)

**Comment by iglesias** [comment]
Thanks for the pointers, I will check them.

**Comment by iglesias** [comment]
I understood it for the json parser example with the standard containers and started taking a look at the ctjs example. Thanks again.
