### ISSUE TITLE
Documentation wrong?

### ISSUE THREAD

**Issue by tomuben** [peter-winter/ctpg#78]
In https://github.com/peter-winter/ctpg?tab=readme-ov-file#regular-expressions it says the sequence for escaped character in hex format is:
```
\\x20
```
But in my tests it looks like it is actually 
```
\x20
```

And thanks for the project. I find it great :) .

**Comment by peter-winter** [comment]
Yes. Nicely spotted. Thank you.
Thank you for the kind words, it means a lot.
